Assignment 4
Gustavo-1300/assignment1 pull request #6
Opened 2023-03-10 09:56 UTC by Gustavo-1300

2023-03-10 14:29 UTC, MrCordeiro commented on Tests/fixtures/mock_date.py
> +    return data
**comment**: An alternative to having the fixture data inside a python script, is to use json files. The advantage is that you can easily generate them with `df.to_json(orient="table")` from a notebook. The json file also includes the table schema, which is also nice.

2023-03-10 15:11 UTC, MrCordeiro requested changes
(I still didn't see the cleaning.py, after weekly I finished)

Very good overall! I wonder if pylint complained about the too-few-public-methods?
 
Btw, why rename "tests" -> "Tests"?

2023-03-10 15:11 UTC, MrCordeiro commented on Tests/test_cleaning.py
> +def fixture_raw():
```suggestion
@pytest.fixture(scope="module")
def fixture_raw() -> pd.DataFrame:
```

Without the scope, pytest will recreate this fixture every time a test calls it. On large code bases, this can make your test suite really slow.

(this comment also applies to the other fixtures)

2023-03-10 15:11 UTC, MrCordeiro commented on Tests/test_cleaning.py
> +    return pd.DataFrame(data_with_floats())
**suggestion**: Your fixtures could be move to `conftest.py`. 

The advantages are:
1. `conftest.py` is a special file in pytest that allows your fixtures to be reused in any test. As it stands, you can only use the fixtures in this module.
2. Fixtures are easier to find when you put them all together.

2023-03-10 15:11 UTC, MrCordeiro commented on Tests/test_main.py
> +    countries_list_expected = [
**Question**: Why are you using a TestCase here? Wouldn't this be simpler:

```python
def test_list_country():
    """Test Country list function"""
    expected = [
        "AL",
        "AM",
        # rest of list...
        "XK",
    ]
    assert Country.list() == expected
```

2023-03-10 15:11 UTC, MrCordeiro commented on life_expectancy/data_interface.py
> +        raise ValueError('File extension not valid!')
As the number of options increase, it will become a massive if then else. Why not leverage the use of classes instead?

Here's a suggestion using enums. You can make your Enum class to automatically detect which value to use from the file, like this:

```python
class LoaderOption(Enum):
    TSV= DataLoaderTSV
    ZIP= DataLoaderCompressed
    
    @classmethod
    def from_path(cls, path: Path):
        for member in cls:
            if member.name.lower() == path.suffix:
                return member
        raise ValueError(f"No member found with suffix {suffix}")
```

Then you just call like this:

```python
data_loader = LoaderOption.from_file("my_file_here.zip")()
```

2023-03-10 15:11 UTC, MrCordeiro commented on life_expectancy/main.py
> +    EU28 = 'EUROPEAN_UNION_28'
**suggestion**: Mode the Region to a region.py module to better separate concerns.

2023-03-10 15:11 UTC, MrCordeiro commented on life_expectancy/main.py
> +            print(f'{args.region} is not a valid region')
Why there are nested try-except blocks here? One should do it...
In fact.. you don't need a try-expect at all! The enum validates the error automatically, see? Even the error message is the same

![image](https://user-images.githubusercontent.com/20598571/224347539-e9e53766-d92e-4613-bf78-a876b4562dcf.png)

2023-03-10 15:11 UTC, MrCordeiro commented on life_expectancy/main.py
> +    data_interface.load_data()
I have now noticed your Loader class actually loads _and_ cleans the data. So calling it a "Loader" is a bit misleading. My suggestion is for you to rename it `ETL` or `Processor` or `Pipeline`

2023-03-10 15:11 UTC, MrCordeiro commented on life_expectancy/data_interface.py
> +        self.data = self.data[self.data['region']==region]
```suggestion
    def filter_data(self, region: Region) ->pd.DataFrame:
        """Filter DataFrame by region"""

        self.data = self.data[self.data['region']==region.name]
```

You have a Region type. Why not make use of it?

2023-03-10 15:11 UTC, MrCordeiro commented on life_expectancy/main.py
> +    )
Move from line 99 (data_interface = ...) to save_data into a function called main. That way you can have an integration test.

2023-03-10 16:21 UTC, MrCordeiro reviewed
Your `save_data` looks a bit lost. 

Why don't you add it to your interface, call it something more appropriate (like ETL), and then transform the operations inside cleaning.py into the different implementations of the how the `tsv` ETL and the `json.zip` ETL implement the `transform`step?

2023-03-10 16:21 UTC, MrCordeiro commented on life_expectancy/cleaning.py
>  def save_data( #pylint: disable=useless-return
Why are you disabling this warning?

2023-03-10 16:21 UTC, MrCordeiro commented on life_expectancy/cleaning.py
>      )
The comment on line 84 is lying... you are not getting the file path (as they are provided as args)

This function seems a little lost in this module. It doesn't clean anything, nor it is every used together with the other functions. I suggest you move it to the place where you do the rest of your ETL, or maybe leave it inside main since it's a super small function that's only used there.

2023-03-10 16:21 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +def transform_data_into_tabular(
This does more than transform data into tabular format though... Either the name could be improved or this could be split into two. Alternatively, you can move this as a function inside your DataCleanerCSV class

2023-03-13 11:06 UTC, Gustavo-1300 commented on Tests/test_main.py
> +    countries_list_expected = [
But using the equal takes into consideration the order of the list and the test would fail if, for some region countries were in a different order which in my Enum is indifferent the order they are on. Additionally, if I were to change the list function to print is some specific order this test would then fail.

2023-03-13 11:06 UTC, Gustavo-1300 commented on life_expectancy/cleaning.py
>      )
I changed the name of the file to etl so I think it now makes more sense to be a part of the whole module

2023-03-13 11:06 UTC, Gustavo-1300 commented on life_expectancy/main.py
> +    EU28 = 'EUROPEAN_UNION_28'
They are basically the same data so I think it makes more sense for both to be in the same file

2023-03-13 11:06 UTC, Gustavo-1300 commented on life_expectancy/main.py
> +            print(f'{args.region} is not a valid region')
I need to check both lists and if the first returns an error to check the second one

2023-03-13 11:06 UTC, Gustavo-1300 commented on life_expectancy/main.py
> +    data_interface.load_data()
I changed it the file name to ETL

2023-03-13 12:17 UTC, MrCordeiro commented on Tests/test_main.py
> +    countries_list_expected = [
There's an easier way to make it clear that the list doesn't matter, using sets:

```suggestion
    difference = set( Country.list()) ^ set(expected )
    assert not difference
```
It's strange to see a pytest test suite using unittest.TestCase

2023-03-13 13:31 UTC, MrCordeiro commented on life_expectancy/main.py
> +            print(f'{args.region} is not a valid region')
This is perhaps a signal that having 2 enums for the same purpose may not be the best strategy. You have to validate twice and you're overriding the `Country` ValueError with the `Region` ValueError, making the difference between them blurrier.

Also, you are just printing the filter was invalid. The code will continue to run and break when passing the `region` parameter to the `filter_data`. The error code will be that you can't pass none as an argument, making it harder for the reader to understand what is going one.

If you really really want to have both enums, may you have to create another class that inherits both of them:

```python
class RegionFilter(Country, Region):
    pass
```

By having 2 try-except blocks, you are missing out on the main feature of an Enum: to help with validations

2023-03-13 13:40 UTC, MrCordeiro requested changes
I think there are only 3 issues left:

- [ ] The double try-except block
- [ ] The lack of a main functions that encompasses the actions taken by your interface
- [ ] The use of TestCase inside a pytest test

2023-03-16 18:16 UTC, MrCordeiro approved these changes
🚀🚀🚀🚀

2023-03-16 18:16 UTC, MrCordeiro commented on life_expectancy/main.py
> +Regions = Enum('Regions', [(i.name, i.value) for i in chain(Countries, Instituions)])
Haha, boa! Se safaste!

(imagino que `Region.list()` não retornará nada, mas tudo bem, pois não estás a usar isso em nenhum canto)

2023-03-17 09:48 UTC, merged